name: doodling_prototype
description: "A prototype for a lan based chat application"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^6.0.1 
  mac_address: ^1.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.2
  socket_io_client_flutter: ^2.0.0
  socket_io_client: ^2.0.3+1
  file_picker: ^8.0.7
  flutter_sound: 9.6.0
  multicast_dns: ^0.3.2+7
  bonsoir: ^5.1.10


  cupertino_icons: ^1.0.8
  device_info: ^2.0.3
  firebase_app_check: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
