// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcPL6UKFpxHPtY7-_kU7IBc59WcG1ck8Y',
    appId: '1:1098391614631:web:4334709e836a8688c91782',
    messagingSenderId: '1098391614631',
    projectId: 'doodlingprototype',
    authDomain: 'doodlingprototype.firebaseapp.com',
    storageBucket: 'doodlingprototype.appspot.com',
    measurementId: 'G-BH3LNHGTK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYW3sP0SyEU0Op4RZmp0sJRkK4ovVtZ5Y',
    appId: '1:1098391614631:android:029253b8c7f27a3ac91782',
    messagingSenderId: '1098391614631',
    projectId: 'doodlingprototype',
    storageBucket: 'doodlingprototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsjy7_q0gCwM7qAOBf8AafDb9TqIftHhc',
    appId: '1:1098391614631:ios:e87f5d8f512bbeffc91782',
    messagingSenderId: '1098391614631',
    projectId: 'doodlingprototype',
    storageBucket: 'doodlingprototype.appspot.com',
    iosClientId: '1098391614631-1ijqdk8iqvpnqg579skk4glgaa2rn8i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodlingPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsjy7_q0gCwM7qAOBf8AafDb9TqIftHhc',
    appId: '1:1098391614631:ios:e87f5d8f512bbeffc91782',
    messagingSenderId: '1098391614631',
    projectId: 'doodlingprototype',
    storageBucket: 'doodlingprototype.appspot.com',
    iosClientId: '1098391614631-1ijqdk8iqvpnqg579skk4glgaa2rn8i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodlingPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcPL6UKFpxHPtY7-_kU7IBc59WcG1ck8Y',
    appId: '1:1098391614631:web:3f9acc1439841ee7c91782',
    messagingSenderId: '1098391614631',
    projectId: 'doodlingprototype',
    authDomain: 'doodlingprototype.firebaseapp.com',
    storageBucket: 'doodlingprototype.appspot.com',
    measurementId: 'G-C8FEV7RGS6',
  );

}